// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace kafka.commande.messages.Schemas
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class Header : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"Header\",\"namespace\":\"kafka.commande.messages.Schemas\",\"fields\":[{\"name\"" +
				":\"msg_id\",\"type\":\"string\"},{\"name\":\"msg_date\",\"type\":\"string\"}]}");
		private string _msg_id;
		private string _msg_date;
		public virtual Schema Schema
		{
			get
			{
				return Header._SCHEMA;
			}
		}
		public string msg_id
		{
			get
			{
				return this._msg_id;
			}
			set
			{
				this._msg_id = value;
			}
		}
		public string msg_date
		{
			get
			{
				return this._msg_date;
			}
			set
			{
				this._msg_date = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.msg_id;
			case 1: return this.msg_date;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.msg_id = (System.String)fieldValue; break;
			case 1: this.msg_date = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
