// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace kafka.commande.messages.Schemas
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class Message : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""Message"",""namespace"":""kafka.commande.messages.Schemas"",""fields"":[{""name"":""header"",""type"":{""type"":""record"",""name"":""Header"",""namespace"":""kafka.commande.messages.Schemas"",""fields"":[{""name"":""msg_id"",""type"":""string""},{""name"":""msg_date"",""type"":""string""}]}},{""name"":""Body"",""type"":""string""}]}");
		private kafka.commande.messages.Schemas.Header _header;
		private string _Body;
		public virtual Schema Schema
		{
			get
			{
				return Message._SCHEMA;
			}
		}
		public kafka.commande.messages.Schemas.Header header
		{
			get
			{
				return this._header;
			}
			set
			{
				this._header = value;
			}
		}
		public string Body
		{
			get
			{
				return this._Body;
			}
			set
			{
				this._Body = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.header;
			case 1: return this.Body;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.header = (kafka.commande.messages.Schemas.Header)fieldValue; break;
			case 1: this.Body = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
